# Generated by Django 5.0.2 on 2024-02-13 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Введите год выпуска автомобиля', validators=[django.core.validators.MinValueValidator(1940)], verbose_name='Год')),
                ('type_of_body', models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('UNIVERSAL', 'Универсал'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Внедорожник'), ('CABRIOLET', 'Кабриолет')], max_length=15, verbose_name='Тип кузова')),
                ('transmission', models.CharField(choices=[('MECHANICS', 'Механика'), ('AUTOMAT', 'Автомат')], max_length=15, verbose_name='Коробка передач')),
                ('gasoline', models.CharField(choices=[('ELECTRO', 'Электро'), ('BENZIN', 'Бензин'), ('DIESEL', 'Дизель'), ('GAS', 'Газ')], max_length=30, verbose_name='Тип топлива')),
                ('wheel', models.CharField(choices=[('LEFT', 'Левый'), ('RIGTH', 'Правый')], max_length=10, verbose_name='Руль')),
                ('color', models.CharField(choices=[('BLACK', 'Черный'), ('WHITE', 'Белый'), ('BROWN', 'Коричневый'), ('SILVER', 'Серебристый'), ('GREEN', 'Зеленый'), ('RED', 'Красный'), ('YELLOW', 'Желтый')], max_length=50, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auto_photos/')),
                ('price_currency', models.CharField(choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('location', models.CharField(choices=[('BISHKEK', 'Бишкек'), ('TOKMOK', 'Токмок'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы')], max_length=100, verbose_name='локация')),
                ('ranting', models.CharField(choices=[('FROM 6 TO 24 HOURS', 'От 6 до 24 часов'), ('FROM 1 TO 7 DAYS', 'От 1 до 7 дней'), ('FROM 1 WEEK TO MONTH', 'От 1 недели до месяца')], max_length=60, verbose_name='аренда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APPARTMENT', 'КВАРТИРА'), ('COMMERCIAL_ESTATE', 'КОММЕРЧЕСКАЯ НЕДВИЖИМОСТЬ'), ('PRIVATE HOUSE', 'ЧАСТНЫЙ ДОМ')], max_length=100, verbose_name='Недвижимость')),
                ('location', models.CharField(choices=[('BISHKEK', 'Бишкек'), ('TOKMOK', 'Токмок'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы')], max_length=100, verbose_name='локация')),
                ('price_currency', models.CharField(choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('number_of_rooms', models.CharField(choices=[('1 ROOM', '1 КОМНАТА'), ('2 ROOMS', '2 КОМНАТЫ'), ('3 ROOMS', '3 КОМНАТЫ'), ('4 ROOMS', '4 КОМНАТЫ'), ('5 ROOMS', '5 КОМНАТЫ'), ('6 ROOMS', '6 КОМНАТЫ'), ('7 ROOMS', '7 КОМНАТЫ')], max_length=100, verbose_name='Количество комнат')),
                ('square', models.IntegerField(verbose_name='Площадь(м2)')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Этаж')),
                ('year_of_buildings', models.CharField(choices=[('UNTILL 19650', 'До 1950'), ('1950-1959', '1950-1959'), ('1960-1969', '1960-1969'), ('1970-1979', '1970-1979'), ('1980-1989', '1980-1989'), ('1990-1999', '1990-1999'), ('2000-2009', '2000:2009'), ('2010-2019', '2010-2019'), ('2020-current', '2020-наст.время')], max_length=100, verbose_name='Год постройки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
    ]
