# Generated by Django 5.0.2 on 2024-02-13 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Черный'), ('WHITE', 'Белый'), ('BROWN', 'Коричневый'), ('SILVER', 'Серебристый'), ('GREEN', 'Зеленый'), ('RED', 'Красный'), ('YELLOW', 'Желтый')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='gasoline',
            field=models.CharField(blank=True, choices=[('ELECTRO', 'Электро'), ('BENZIN', 'Бензин'), ('DIESEL', 'Дизель'), ('GAS', 'Газ')], max_length=30, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='location',
            field=models.CharField(blank=True, choices=[('BISHKEK', 'Бишкек'), ('TOKMOK', 'Токмок'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы')], max_length=100, verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='ranting',
            field=models.CharField(blank=True, choices=[('FROM 6 TO 24 HOURS', 'От 6 до 24 часов'), ('FROM 1 TO 7 DAYS', 'От 1 до 7 дней'), ('FROM 1 WEEK TO MONTH', 'От 1 недели до месяца')], max_length=60, verbose_name='аренда'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmission',
            field=models.CharField(blank=True, choices=[('MECHANICS', 'Механика'), ('AUTOMAT', 'Автомат')], max_length=15, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='type_of_body',
            field=models.CharField(blank=True, choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('UNIVERSAL', 'Универсал'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Внедорожник'), ('CABRIOLET', 'Кабриолет')], max_length=15, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='wheel',
            field=models.CharField(blank=True, choices=[('LEFT', 'Левый'), ('RIGTH', 'Правый')], max_length=10, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.IntegerField(blank=True, help_text='Введите год выпуска автомобиля', validators=[django.core.validators.MinValueValidator(1940)], verbose_name='Год'),
        ),
    ]
